### ISSUE TITLE
Some names are displayed as .lens

### ISSUE THREAD

**Issue by 0xJuancito** [juanscolari/who-is-in-lens-web#1]
Some names are displayed as `.lens`

<img width="233" alt="Screen Shot 2022-08-30 at 23 53 07" src="https://user-images.githubusercontent.com/12957692/187582193-ab6ac818-40de-4133-82e0-2414386c6597.png">

**Comment by juancito-dev** [comment]
fixed in https://github.com/juanscolari/who-is-in-lens/commit/3c633b8c73c30e3526b0c81bc0d3080190c4cbdb
