### ISSUE TITLE
Scale API requests

### ISSUE THREAD

**Issue by 0xJuancito** [juanscolari/who-is-in-lens-web#7]
The current Twitter API limit for following is 15 requests every 15 minutes as the documentation states: https://developer.twitter.com/en/docs/twitter-api/users/follows/migrate

Ideas:
- Support rotating multiple keys
- Add sign in with Twitter to augment the API quota for each user

**Comment by juancito-dev** [comment]
Solved in https://github.com/juanscolari/who-is-in-lens-web/issues/15
