### ISSUE TITLE
Mirror Twitter content on Lens

### ISSUE THREAD

**Issue by 0xJuancito** [juanscolari/who-is-in-lens-web#8]
Mirror Twitter content on Lens.

Similar ideas
- Mirror Lens content on Twitter: [Reflect](https://reflect.withlens.app/)
- Chrome plugin to embed "Post on Lens" on the Twitter site: [Reroot](https://chrome.google.com/webstore/detail/reroot/ogongagcipmopmfgdblppemhmjbnpkme/related)

**Comment by juancito-dev** [comment]
Closing. Not related to the project. May be a good fit for another one
